workflows:
  android-app:
    name: Don't Press Android App
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      java: 11
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - user_email@example.com 